# Generated by Django 3.2.13 on 2022-04-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('Record', models.DateField(auto_created=True)),
                ('Roll_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Date_of_admission', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
