# Generated by Django 3.2.13 on 2022-04-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=30)),
                ('Emp_sal', models.IntegerField()),
                ('Emp_city', models.CharField(max_length=30)),
            ],
        ),
    ]
