# Generated by Django 3.2.13 on 2022-04-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelFeedback',
            new_name='Feedback',
        ),
    ]
