# Generated by Django 3.2.13 on 2022-04-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_rename_modelfeedback_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='ModelFeedback',
        ),
    ]
