# Generated by Django 3.2.13 on 2022-04-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0003_rename_feedback_modelfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfeedback',
            name='age',
            field=models.IntegerField(max_length=5),
        ),
    ]
