# Generated by Django 3.2.13 on 2022-04-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0004_alter_modelfeedback_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfeedback',
            name='age',
            field=models.IntegerField(),
        ),
    ]
